# -------------------- app info <----------------------
# 项目名
app.name = chatting-rag-boot
# 端口号
app.port = 8001
# 版本号
app.version = 2026.04.22
# -------------------- app info >----------------------

# -------------------- docker info <----------------------
docker.repository.name = mingsha/app
docker.image.name = chatting-rag-boot
docker.image.tag = 2026.04.22
docker.container.name = chatting-rag-boot
# -------------------- docker info >----------------------

# -------------------- helm info <----------------------
helm.image = mingsha/app/chatting-rag-boot
helm.namespace = mingsha
# -------------------- helm info >----------------------
